// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Db;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ItemContext))]
    [Migration("20220915164116_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("api.Db.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9c1f05af-ff16-4361-8491-579d642a408b"),
                            Description = "Pick up groceries",
                            Name = "Item 1"
                        },
                        new
                        {
                            Id = new Guid("ef497495-d977-4f6b-9ad5-c20e76914436"),
                            Description = "Go to bank",
                            Name = "Item 2"
                        },
                        new
                        {
                            Id = new Guid("7741c67d-666b-43cc-8565-b8dbe6285210"),
                            Description = "Go to post office",
                            Name = "Item 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
